# Generated by Django 4.2.11 on 2024-03-11 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valueId", models.CharField(max_length=10)),
                ("value", models.CharField(max_length=10)),
                ("stock", models.CharField(max_length=50)),
                ("shipping", models.CharField(max_length=100)),
                ("isSameDayShippingWindow", models.BooleanField(default=False)),
                ("quantitySourceType", models.CharField(max_length=50)),
                ("href", models.URLField()),
                ("selectable", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="app.product",
                    ),
                ),
            ],
        ),
    ]
